config/routes.rb
Rails.application.routes.draw do
  post 'omise_callback', to: 'omise#omise_callback'

  authenticate :user, lambda { |u| u.admin? } do
    mount Crono::Web, at: '/admin/scheduler'
  end

  devise_for :users
  resources :cars
  get 'home/index'
  get 'user_dashboard/dashboard', to: 'user_dashboard#dashboard', as: 'dashboard'
  get 'user_dashboard/edit', to: 'user_dashboard#edit', as: 'user_dashboard_edit'
  patch  'user_dashboard/update/:user_id', to: 'user_dashboard#update', as: 'user_dashboard_update'
  get 'user_dashboard/upload_driving_license', to: 'user_dashboard#upload_driving_license', as: 'upload_driving_license'
  patch  'user_dashboard/upload_driving_license/:user_id', to: 'user_dashboard#update_driving_license', as: 'update_driving_license'
  post 'api/toll_fee_record/create', to: 'toll_fee_records#create', as: 'create_toll_fee_record'
  resources :toll_fee_records, only: [:index, :show]
  resources :bills, only: [:index, :create, :show]
  patch 'bills/update_slip/:id', to: 'bills#update_slip', as: 'update_slip'
  get 'bills_unconfirmed', to: 'bills#unconfirmed_index', as: 'unconfirmed_bills'
  get 'bills_unconfirmed/:id', to: 'bills#unconfirmed_show', as: 'unconfirmed_bill'
  post 'bills_unconfirmed/:id', to: 'bills#unconfirmed_update', as: 'unconfirmed_bill_update'
  post 'bills_update_barcode/:id', to: 'bills#update_barcode', as: 'bill_barcode_update'
  post 'api/publish_license', to: 'toll_fee_records#create_with_image', as: 'create_with_image'
  get 'export_bill/:id', to: 'bills#export_pdf', as: 'export_pdf'
  # get 'admin/data_dashboard', to: 'home#dummy_rails_admin', as: 'rails_admin' # dummy to fake path when remove rails admin for debug
  mount RailsAdmin::Engine => '/admin/data_dashboard', as: 'rails_admin'
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/toll_fee_record.rb
class TollFeeRecord < ApplicationRecord
  belongs_to :toll_booth
  belongs_to :car
  belongs_to :bill, optional: true
  has_attached_file :image, styles: { :large =>   "640x480>", medium: "300x300>", thumb: "100x100>" },
                    default_url: "/images/missing.png"
  validates_attachment_content_type :image, :content_type => %w(image/jpeg image/jpg image/png)

end

app/controllers/toll_fee_records_controller.rb
# require 'multipart_parser/reader'

class TollFeeRecordsController < ApplicationController
  protect_from_forgery with: :null_session # disable CRSF protection for api controller
  before_action :authenticate_user!, except: [:create, :create_with_image]
  before_action :authenticate_tollbooth, only: [:create, :create_with_image]

  # List all user_dashboard toll fee records
  def index
    @toll_fee_records = current_user.toll_fee_records.order("created_at DESC")
  end

  def show
    # Basically authorize resource here
    @toll_fee_record = TollFeeRecord.find_by_id(params[:id])
    unless @toll_fee_record.car.user.id == current_user.id
      flash[:error] = "Unauthorized"
      redirect_to dashboard_path
    end
  end

# https://stackoverflow.com/questions/23153099/rails-get-multipart-form-data-post-request-parameters-with-same-name/23215937
  def create
    if @toll_booth
      @car = Car.find_by_license_plate_number(params[:license_plate_number])
      if @car
        @toll_fee_record = TollFeeRecord.create({toll_booth: @toll_booth, car:@car, timestamp: DateTime.now})
        if @toll_fee_record
          NotificationMailer.notify_new_record(@car.user, @toll_fee_record).deliver
          respond_to do |format|
            format.json{ render json: '{"status": "success"}',status: :created}
          end
        else
          respond_to do |format|
            format.json{ render json: '{"status": "internal database error"}',status: :internal_server_error}
          end
        end

      else
        # Notfound send alert
        respond_to do |format|
          format.json{ render json: '{"status": "not found"}', status: :unprocessable_entity}
        end
      end
    else
      respond_to do |format|
        format.json{ render json: '{"status": "unauthorized"}', status: :unauthorized}
      end
    end
  end

  def create_with_image
    if @toll_booth
      data = JSON.parse params["json"]
      image = params["image"]
      @car = Car.find_by_license_plate_number(data["license_plate_number"])
      if @car
        @toll_fee_record = TollFeeRecord.create({toll_booth: @toll_booth, car:@car, timestamp: DateTime.parse(data["timestamp"]), image: image})
        if @toll_fee_record
          NotificationMailer.notify_new_record(@car.user, @toll_fee_record).deliver
          respond_to do |format|
            format.any{ render json: '{"status": "success"}',status: :created, content_type: 'application/json'}
          end
        else
          respond_to do |format|
            format.any{ render json: '{"status": "internal database error"}', status: :internal_server_error, content_type: 'application/json'}
          end
        end

      else
        # Notfound send alert
        respond_to do |format|
          format.any{ render json: '{"status": "not found"}', status: :unprocessable_entity, content_type: 'application/json'}
        end
      end
    else
      respond_to do |format|
        format.any{ render json: '{"status": "unauthorized"}', status: :unauthorized, content_type: 'application/json'}
      end
    end
  end

  private
    def authenticate_tollbooth
      authenticate_or_request_with_http_token do |token, options|
        @toll_booth = TollBooth.where(api_key: token).first
        @toll_booth
      end
    end


end

app/helpers/toll_fee_records_helper.rb
module TollFeeRecordsHelper
end

app/views/toll_fee_records/_row.html.erb
<tr>
  <td class="hidden-xs"><%= order %></td>
  <td> <%= record.toll_booth.name %> </td>
  <td> <%= record.car.license_plate_number %> </td>
  <td> <%= record.timestamp %> </td>
  <td> <%= record.toll_booth.toll_fee %> </td>
  <td align="center">
    <%= link_to toll_fee_record_path(record), class: 'btn btn-default' do %>
        <em class="fa fa-ellipsis-h"></em>
    <% end %>
  </td>
</tr>

app/views/toll_fee_records/_table.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="card">
    <div class="card-header">
      <div class="row">
        <div class="col col-xs-6">
          <h3 class="card-title">Your Toll Fee Records</h3>
        </div>
      </div>
    </div>
    <div class="card-body">
      <table class="table table-striped table-bordered table-list">
        <thead>
        <tr>
          <th class="hidden-xs">#</th>
          <th>Toll gate</th>
          <th>Car</th>
          <th>Time</th>
          <th>Fee</th>
          <th>View Details</th>
        </tr>
        </thead>
        <tbody>
        <% i = 1 %>
          <% toll_fee_records.each do |record| %>
            <%= render 'toll_fee_records/row', record: record, order: i %>
            <% i = i + 1 %>
          <% end %>
        </tbody>
      </table>

    </div>
    <div class="card-footer">
      <!--
      <div class="row">
        <div class="col col-xs-4">Page 1 of 5
        </div>
        <div class="col col-xs-8">
          <ul class="pagination hidden-xs pull-right">
            <li><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">5</a></li>
          </ul>
          <ul class="pagination visible-xs pull-right">
            <li><a href="#">«</a></li>
            <li><a href="#">»</a></li>
          </ul>
        </div>
      </div>
      -->
    </div>
  </div>
</div>

app/views/toll_fee_records/index.html.erb
<%= render 'toll_fee_records/table', toll_fee_records: @toll_fee_records %>

app/views/toll_fee_records/show.html.erb
<div class="container" style="margin-top:10px;">
  <div class="row justify-content-center">
    <div class="col col-lg-6 col-lg-offset-3">
      <div class="card" style="width:600px">
        <div class="card-header">
          <h3 class="card-title">Toll Fee Record Details: Ref ID <%= @toll_fee_record.id %></h3>
        </div>
          <%= image_tag @toll_fee_record.image.url(:medium), class:'card-img-top', alt: 'Toll fee record image' %>
        <div class="card-body">
          <table class="table">
            <tbody>
            <tr>
              <td>Passing Date:</td>
              <td><%= @toll_fee_record.timestamp %></td>
            </tr>
            <tr>
              <td>Toll Gate:</td>
              <td> <%= @toll_fee_record.toll_booth.name %> </td>
            </tr>
            <tr>
              <td>Toll Fee:</td>
              <td> <%= @toll_fee_record.toll_booth.toll_fee %> </td>
            </tr>

            <tr>
            <tr>
              <td>Car:</td>
              <td> <%= link_to @toll_fee_record.car.license_plate_number, car_path(@toll_fee_record.car) %> </td>
            </tr>
            <tr>
              <td>Issued Bill: </td>
              <td>
                <% if @toll_fee_record.bill.nil? %>
                  None
                <% else %>
                  <%= link_to "#" + @toll_fee_record.bill.id.to_s, bill_path(@toll_fee_record.bill) %>
                <% end %>
              </td>
            </tr>

            </tbody>
          </table>
        </div>
        <div class="card-footer text-center">
        </div>
      </div>
    </div>
  </div>

</div>