config/routes.rb
Rails.application.routes.draw do
  post 'omise_callback', to: 'omise#omise_callback'

  authenticate :user, lambda { |u| u.admin? } do
    mount Crono::Web, at: '/admin/scheduler'
  end

  devise_for :users
  resources :cars
  get 'home/index'
  get 'user_dashboard/dashboard', to: 'user_dashboard#dashboard', as: 'dashboard'
  get 'user_dashboard/edit', to: 'user_dashboard#edit', as: 'user_dashboard_edit'
  patch  'user_dashboard/update/:user_id', to: 'user_dashboard#update', as: 'user_dashboard_update'
  get 'user_dashboard/upload_driving_license', to: 'user_dashboard#upload_driving_license', as: 'upload_driving_license'
  patch  'user_dashboard/upload_driving_license/:user_id', to: 'user_dashboard#update_driving_license', as: 'update_driving_license'
  post 'api/toll_fee_record/create', to: 'toll_fee_records#create', as: 'create_toll_fee_record'
  resources :toll_fee_records, only: [:index, :show]
  resources :bills, only: [:index, :create, :show]
  patch 'bills/update_slip/:id', to: 'bills#update_slip', as: 'update_slip'
  get 'bills_unconfirmed', to: 'bills#unconfirmed_index', as: 'unconfirmed_bills'
  get 'bills_unconfirmed/:id', to: 'bills#unconfirmed_show', as: 'unconfirmed_bill'
  post 'bills_unconfirmed/:id', to: 'bills#unconfirmed_update', as: 'unconfirmed_bill_update'
  post 'bills_update_barcode/:id', to: 'bills#update_barcode', as: 'bill_barcode_update'
  post 'api/publish_license', to: 'toll_fee_records#create_with_image', as: 'create_with_image'
  get 'export_bill/:id', to: 'bills#export_pdf', as: 'export_pdf'
  # get 'admin/data_dashboard', to: 'home#dummy_rails_admin', as: 'rails_admin' # dummy to fake path when remove rails admin for debug
  mount RailsAdmin::Engine => '/admin/data_dashboard', as: 'rails_admin'
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %>">
      <button class="close" data-dismiss="alert" aria-label="close">&times;</button>
      <%= message %>
    </div>
<% end %>

app/views/shared/_navigation_bar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <%= link_to root_path, class: "navbar-brand" do %>
    TollBooth System <em class="fa fa-hdd"></em>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExample04">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
          </li>
          <% if current_user.admin? %>
            <li class="nav-item active">
              <%= link_to "Data Dashboard", rails_admin_path, class: "nav-link"  %>
            </li>
          <li class="nav-item active">
            <%= link_to "Scheduler Dashboard", crono_web_path, class: "nav-link" %>
          </li>
            <li class="nav-item active">
              <%= link_to "Confirm Bills", unconfirmed_bills_path, class: "nav-link"  %>
            </li>
          <% else %>
            <li class="nav-item active">
              <%= link_to "Cars", cars_path, class: "nav-link"  %>
            </li>
            <li class="nav-item active">
              <%= link_to "Toll Records", toll_fee_records_path, class: "nav-link"  %>
            </li>
            <li class="nav-item active">
              <%= link_to "Bills", bills_path, class: "nav-link"  %>
            </li>
          <% end %>

      <% end %>
    </ul>

    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <% if current_user.admin? %>
          <li class="list-group-item list-group-item-danger">
            <p>ADMIN</p>
          </li>
        <% end %>
        <li class="nav-item active">
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link"  %>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to "Sign in", new_user_session_path, class: "nav-link"  %>
        </li>
        <li class="nav-item active">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link"  %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>