config/routes.rb
Rails.application.routes.draw do
  post 'omise_callback', to: 'omise#omise_callback'

  authenticate :user, lambda { |u| u.admin? } do
    mount Crono::Web, at: '/admin/scheduler'
  end

  devise_for :users
  resources :cars
  get 'home/index'
  get 'user_dashboard/dashboard', to: 'user_dashboard#dashboard', as: 'dashboard'
  get 'user_dashboard/edit', to: 'user_dashboard#edit', as: 'user_dashboard_edit'
  patch  'user_dashboard/update/:user_id', to: 'user_dashboard#update', as: 'user_dashboard_update'
  get 'user_dashboard/upload_driving_license', to: 'user_dashboard#upload_driving_license', as: 'upload_driving_license'
  patch  'user_dashboard/upload_driving_license/:user_id', to: 'user_dashboard#update_driving_license', as: 'update_driving_license'
  post 'api/toll_fee_record/create', to: 'toll_fee_records#create', as: 'create_toll_fee_record'
  resources :toll_fee_records, only: [:index, :show]
  resources :bills, only: [:index, :create, :show]
  patch 'bills/update_slip/:id', to: 'bills#update_slip', as: 'update_slip'
  get 'bills_unconfirmed', to: 'bills#unconfirmed_index', as: 'unconfirmed_bills'
  get 'bills_unconfirmed/:id', to: 'bills#unconfirmed_show', as: 'unconfirmed_bill'
  post 'bills_unconfirmed/:id', to: 'bills#unconfirmed_update', as: 'unconfirmed_bill_update'
  post 'bills_update_barcode/:id', to: 'bills#update_barcode', as: 'bill_barcode_update'
  post 'api/publish_license', to: 'toll_fee_records#create_with_image', as: 'create_with_image'
  get 'export_bill/:id', to: 'bills#export_pdf', as: 'export_pdf'
  # get 'admin/data_dashboard', to: 'home#dummy_rails_admin', as: 'rails_admin' # dummy to fake path when remove rails admin for debug
  mount RailsAdmin::Engine => '/admin/data_dashboard', as: 'rails_admin'
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bill.rb
class Bill < ApplicationRecord
  include MyOmise
  has_many :toll_fee_records, dependent: :nullify
  belongs_to :user
  before_save :default_values
  has_attached_file :payment_evidence, styles: { :large =>   "500x500>" },
                    default_url: "/images/missing.png"
  validates_attachment_content_type :payment_evidence, :content_type => %w(image/jpeg image/jpg image/png)

  has_attached_file :barcode_file
  validates_attachment_content_type :barcode_file, content_type: ["image/svg+xml"]

  def exceed_deadline?
    self.payment_deadline < DateTime.now
  end

  def omise_barcode_expired?
    unless self.omise_barcode_expires_at.blank?
      self.omise_barcode_expires_at < DateTime.now
    end
  end

  def update_attributes_omise_barcode
    #if self.omise_source_id.blank?
      src_data = create_bill_source(self.total_amount)
      if src_data.present?
        self.omise_source_id = src_data['id']
      else
        return false # end flow here
      end
    #end

    # self.save

    if self.omise_barcode_url.blank? || self.omise_barcode_expired?
      charge_data = charge_bill_source(self.omise_source_id, self.id, self.total_amount)
      if charge_data.present?
        self.omise_barcode_created_at = DateTime.parse charge_data['created']
        self.omise_barcode_expires_at = DateTime.parse charge_data['source']['references']['expires_at']
        self.omise_barcode_url = charge_data['source']['references']['barcode']
        self.omise_charge_id = charge_data['id'] # use this for trigger callback
        self.barcode_number = charge_data['source']['references']['reference_number_2']
        self.barcode_file = open(self.omise_barcode_url) # download and save svg file
        true
      else
        false
      end
    else
      false
    end

  end

  private
  def default_values
    if self.payment_confirm.nil?
      self.payment_confirm = false
    end

    if self.payment_deadline.nil?
      self.payment_deadline = 2.weeks.from_now
    end

    # re calc total amount
    unless self.toll_fee_records.nil?
      amount = 0
      self.toll_fee_records.each do |record|
        amount += record.toll_booth.toll_fee
      end
      self.total_amount = amount
    end
  end

end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_bill, only: [:show, :update_slip, :update_barcode,
                                  :unconfirmed_show, :unconfirmed_update, :export_pdf]

  def index
    @bills = current_user.bills.order("created_at DESC")
  end

  # Presereved only for admin to create Bills Manually
  def create
    # get all member in the system
    @users = User.where(admin: false)
    fail_ids = []
    @users.each do |user|
      unissued_records = TollFeeRecord.where(car: user.cars, bill_id:nil) # get all records that not yet issued
      if unissued_records.count > 0
        new_bill = Bill.create({user: user, toll_fee_records: unissued_records, payment_deadline: 2.weeks.from_now})
        if new_bill
          NotificationMailer.notify_new_bill(user,new_bill).deliver
        else
          fail_ids << user.id
        end
      end
    end

    if fail_ids.count > 0
        # TODO -- notify admin
        logger.error('FAILS TO Create Bill for following User IDs:' + fail_ids.to_s )
    end

    flash.now[:success] = "Bill Generated"
    respond_to do |format|
      format.html{ redirect_to dashboard_path }
    end
  end

  def show
    if @bill.payment_confirm
      flash.now[:success] = "This bill has already been paid"
    else
      if @bill.exceed_deadline?
        flash.now[:error] = "ALERT! Already pass the payment deadline, you will be charged"
      else
        flash.now[:alert] = "Warning, you haven't paid this bill yet! or Admin has not confirmed the payment"
      end
    end
  end

  def export_pdf
    render pdf: "Exported_Bill", template: "bills/export_pdf.html.erb", page_size: "A4", encoding: "UTF-8"
  end

  # Must be at least 20 Baht To use this feature
  def update_barcode

    if !@bill.payment_confirm
        if @bill.total_amount >= 20.0
          @bill.payment_method = "barcode"
          st = @bill.update_attributes_omise_barcode
          if st && @bill.save
            respond_to do |format|
              flash[:success] = "Your barcode is successfully generated, please check your email"
              format.html{ redirect_to bill_path(@bill)}
            end
          else
            respond_to do |format|
              flash.now[:error] = "Cannot Update payment Barcode, or the previous barcode is not expired"
              format.html{ redirect_to bill_path(@bill)}
            end
          end
        else
          respond_to do |format|
            flash.now[:error] = "Cannot Create Barcode, total amount must be at least 20 Baht"
            format.html{ redirect_to bill_path(@bill)}
          end
        end


    else
        respond_to do |format|
          flash.now[:error] = "This payment has already confirm!"
          format.html{ redirect_to root_path }
        end
    end
  end

  # For user to manually update slip
  def update_slip
    if !@bill.payment_confirm
      @bill.assign_attributes(params.require(:bill).permit(:payment_evidence))
      @bill.payment_method = "manual"

      if @bill.save
        respond_to do |format|
          flash[:success] = "Successfully Upload Payment Slip, please wait for admin to verify"
          format.html{ redirect_to bill_path(@bill), success: "Successfully Upload Payment Slip, please wait for admin to verify" }
        end
      else
        respond_to do |format|
          flash.now[:error] = "Cannot Upload Payment Slip"
          format.html{ redirect_to bill_path(@bill)}
        end
      end
    else
      respond_to do |format|
        flash.now[:error] = "This payment has already confirm!"
        format.html{ redirect_to root_path }
      end
    end
  end

  # For admins
  def unconfirmed_index
    @bills = Bill.where(payment_method: "manual", payment_confirm: false).where.not(payment_evidence_file_name: [nil, ""])
  end

  def unconfirmed_show
  end

  def unconfirmed_update
    if params[:is_confirmed]
      @bill.payment_confirm = true
      if @bill.save()
        # send email to user (accept)
        NotificationMailer.notify_payment_confirm_accept(@bill.user, @bill).deliver
      else
        flash.now[:error] = "Cannot Persisted to Database"
      end
    else
      @bill.payment_confirm = false
      @bill.payment_evidence.clear
      @bill.payment_method = nil
      if @bill.save()
        # send email to user (reject)
        NotificationMailer.notify_payment_confirm_reject(@bill.user, @bill).deliver
      else
        flash.now[:error] = "Cannot Persisted to Database"
      end
    end
    redirect_to unconfirmed_bills_path
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_bill
    @bill = Bill.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  # def bill_params
  #   # params.require(:bill).permit(:payment_evidence)
  # end

end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_row.html.erb
<tr>
  <td class="hidden-xs"><%= order %></td>
  <td> <%= bill.created_at %> </td>
  <td> <%= bill.payment_deadline %> </td>
  <td> <%= bill.total_amount %> </td>
  <% if bill.payment_confirm %>
  <td> <em class="fa fa-check-circle"></em> </td>
  <% else %>
    <td><p> </p></td>
  <% end %>
  <td align="center">
    <%= link_to bill_path(bill), class: 'btn btn-default' do %>
      <em class="fa fa-ellipsis-h"></em>
    <% end %>
  </td>
</tr>

app/views/bills/_table.html.erb
<div class="col-md-10 col-md-offset-1">

  <div class="card bg-light">
    <div class="card-header">
      <div class="row">
        <div class="col col-lg-6">
          <h3 class="panel-title">Your Bills</h3>
        </div>
      </div>
    </div>
    <div class="card-body">
      <table class="table table-striped table-bordered table-list">
        <thead>
        <tr>
          <th>#</th>
          <th>Issued Date</th>
          <th>Payment Deadline</th>
          <th>Total amount</th>
          <th>Is Paid</th>
          <th>View Details</th>
        </tr>
        </thead>
        <tbody>
        <% i = 1 %>
        <% bills.each do |b| %>
          <%= render 'bills/row', bill: b, order: i %>
          <% i = i + 1 %>
        <% end %>
        </tbody>
      </table>

    </div>
    <div class="panel-footer">
      <!--
      <div class="row">
        <div class="col col-xs-4">Page 1 of 5
        </div>
        <div class="col col-xs-8">
          <ul class="pagination hidden-xs pull-right">
            <li><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">5</a></li>
          </ul>
          <ul class="pagination visible-xs pull-right">
            <li><a href="#">«</a></li>
            <li><a href="#">»</a></li>
          </ul>
        </div>
      </div>
      -->
    </div>
  </div>
</div>

app/views/bills/_unconfirmed_row.html.erb
<% if bill.exceed_deadline? %>
  <tr style="background: #d4585c">
<% else %>
<tr>
<% end %>
  <td class="hidden-xs"><%= order %></td>
  <td> <%= bill.id %> </td>
  <td> <%= bill.user.id %> </td>
  <td> <%= bill.created_at %> </td>
  <td> <%= bill.payment_deadline %> </td>
  <td align="center">
    <%= link_to unconfirmed_bill_path(bill), class: 'btn btn-default' do %>
      <em class="fa fa-ellipsis-h"></em>
    <% end %>
  </td>
</tr>

app/views/bills/export_pdf.html.erb
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Exported Bill</title>

  <style>
    .invoice-box {
      margin: auto;
      padding: 20px;
      border: 1px solid #eee;
      font-size: 16px;
      line-height: 24px;
      font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
      color: #555;
    }

    .invoice-box table {
      width: 100%;
      line-height: inherit;
      text-align: left;
    }

    .invoice-box table td {
      padding: 5px;
      vertical-align: top;
    }

    .invoice-box table tr td:nth-child(2) {
      text-align: right;
    }

    .invoice-box table tr.top table td {
      padding-bottom: 20px;
    }

    .invoice-box table tr.top table td.title {
      font-size: 45px;
      line-height: 45px;
      color: #333;
    }

    .invoice-box table tr.information table td {
      padding-bottom: 40px;
    }

    .invoice-box table tr.heading td {
      background: #eee;
      border-bottom: 1px solid #ddd;
      font-weight: bold;
    }

    .invoice-box table tr.details td {
      padding-bottom: 20px;
    }

    .invoice-box table tr.item td{
      border-bottom: 1px solid #eee;
    }

    .invoice-box table tr.item.last td {
      border-bottom: none;
    }

    .invoice-box table tr.total td:nth-child(2) {
      border-top: 2px solid #eee;
      font-weight: bold;
    }

    @media only screen and (max-width: 600px) {
      .invoice-box table tr.top table td {
        width: 100%;
        display: block;
        text-align: center;
      }

      .invoice-box table tr.information table td {
        width: 100%;
        display: block;
        text-align: center;
      }
    }

    /** RTL **/
    .rtl {
      direction: rtl;
      font-family: Tahoma, 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
    }

    .rtl table {
      text-align: right;
    }

    .rtl table tr td:nth-child(2) {
      text-align: left;
    }
  </style>
</head>

<body>
<div class="invoice-box">
  <table cellpadding="0" cellspacing="0">
    <tr class="top">
      <td colspan="2">
        <table>
          <tr>
            <td class="title">
              TOLLBOOTH SYSTEM
            </td>

            <td>
              Bill Reference ID #: <%= @bill.id %><br>
              Created: <%= @bill.created_at.localtime.strftime("%B %d, %Y") %><br>
              Due: <%= @bill.payment_deadline.strftime("%B %d, %Y") %>
            </td>

          </tr>
        </table>
      </td>
    </tr>

    <tr class="information" style="text-align: left">
      <td colspan="2">
        <table>
          <tr>
            <td>
              TollBooth System, Inc.<br>
              58 Moo 9, Paholyothin Highway<br>
              Khlong Nueng, Pathum Thani 12120
              admin@ait.asia
            </td>

            <td>
              Bill To : <%= @bill.user.get_full_name %><br>
              <%= @bill.user.address %><br>
              Email: <%= @bill.user.email %><br>
              Phone Number: <%= @bill.user.phone_number %>
            </td>
          </tr>
        </table>
      </td>
    </tr>

    <tr class="heading">
      <td>
        Payment Method
      </td>

      <td>
        <% if @bill.payment_method.blank? %>
          Unspecified
        <% elsif @bill.payment_method == "manual" %>
          Manual Transfer
        <% elsif @bill.payment_method == "barcode" %>
          TESCO Lotus Barcode
        <% end %>
      </td>
    </tr>

    <tr class="heading">
      <td>
        Item
      </td>

      <td>
        Price (฿:THB)
      </td>
    </tr>

    <% @bill.toll_fee_records.each do |record| %>
    <tr class="item">
        <td>
          <%= record.toll_booth.name %>
        </td>

        <td>
          ฿<%= record.toll_booth.toll_fee %>
        </td>
    </tr>
      <% end %>
    <tr class="total">
      <td></td>

      <td>
        Total: ฿<%= @bill.total_amount %>
      </td>
    </tr>
  </table>

  <div style="text-align: center">
    <% if @bill.barcode_file.exists? %>
      <%= raw(Paperclip.io_adapters.for(@bill.barcode_file).read) %><br>
      <%= @bill.barcode_number %>
    <% end %>
  </div>

</div>
</body>
</html>

app/views/bills/index.html.erb
<%= render 'bills/table', bills: @bills %>

app/views/bills/show.html.erb
<div class="container" style="margin-top:10px;">
  <div class="row justify-content-center">
    <div class="col col-lg-8 col-lg-offset-2">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Bill Details: Ref ID <%= @bill.id %></h3>
        </div>
        <!--
        <div class="panel-image hide-panel-body">
        </div>
        -->
        <div class="card-body">
          <table class="table">
            <tbody>
            <tr>
              <td>Total Amount:</td>
              <td><%= @bill.total_amount %></td>
            </tr>
            <tr>
              <td>Payment Deadline:</td>
              <td> <%= @bill.payment_deadline %> </td>
            </tr>
            <tr>
              <td>Current payment method:</td>
              <% if @bill.payment_method.blank? %>
                <td> Not Selected </td>
              <% else %>
                <td> <%= @bill.payment_method %> </td>
              <% end %>
            </tr>

            <tr>
              <td>Payment Status:</td>
              <td>
              <% if @bill.payment_confirm %>
                <em class="fa fa-check-circle"></em>
              <% end %>
              </td>
            </tr>

            </tbody>
          </table>
        </div>
        <div class="card-footer" style="text-align: center;">
        <% unless @bill.payment_confirm %>
            <button onclick="toggleUploadSlipForm()" class="btn btn-info"><em class="fa fa-paperclip"></em> Upload Payment Slip
              Attachment</button>
            <%= link_to bill_barcode_update_path(@bill), method: :post, class: "btn btn-info" do %>
              <em class="fa fa-barcode"></em> Generate Tesco Lotus Barcode
            <% end %>
        <% end %>
         <%= link_to export_pdf_path(@bill), :target => '_blank' ,class: "btn btn-danger" do %>
            <em class="fa fa-file-pdf"></em> Export Bill as PDF
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<br><br>
<% if @bill.barcode_file.exists? %>
<div class="row justify-content-center">
  <div class="col-lg-8 col-lg-offset-2 text-center">
    <h3>Tesco Lotus Payment Barcode</h3>
      <%= raw(Paperclip.io_adapters.for(@bill.barcode_file).read) %>
      <p><%= @bill.barcode_number %></p>
    <%if @bill.payment_confirm &&  (@bill.payment_method == "barcode")  %>
      <div class="alert alert-info">
        This Barcode has been used for this bill payment
      </div>
    <% else %>
      <% if @bill.omise_barcode_expired? %>
        <div class="alert alert-danger">
          Your barcode has already expired! please generate a new one.
        </div>
      <% else %>
        <div class="alert alert-success">
          This barcode avaliable until <%= @bill.omise_barcode_expires_at %>
        </div>
      <% end %>
    <% end %>

  </div>
</div>
  <br><br>
<% end %>

<div class="row justify-content-center">

<div id="uploadSlipForm" class="card" style="display: none; width: 600px;">
  <div class="card-header">
    <h3 class="card-title">Upload Payment Slip Attachment</h3>
  </div>
  <div class="card-body">

    <% if @bill.payment_evidence.exists? %>
      <div class="alert alert-warning" role="alert">
        You have already upload the payment slip, re-upload will cause the current one to be deleted
      </div>
      <%= image_tag  @bill.payment_evidence.url, class: "card-img-top"%>
      <div style="text-align: center;">
        <p>Uploaded at <%= @bill.payment_evidence_updated_at %> </p>
      </div>
    <% end %>
    <div class="form">
      <p>Select Your attachment slip</p>
        <%= form_for @bill, url: update_slip_path, html: {multipart: true} do |form| %>
          <div class="form-group">
            <%= form.file_field :payment_evidence %>
          </div>
          <div class="form-group">
            <%= form.submit 'Upload Slip', class: "btn btn-info" %>
          </div>
    </div>

    <% end %>
  </div>

</div>

</div>
<br><br>
<div class="row justify-content-center">
  <h2>Associated Toll Fee Records for this bill</h2>
  <%= render 'toll_fee_records/table', toll_fee_records: @bill.toll_fee_records %>
</div>



<script>
    function toggleUploadSlipForm() {
        var x = document.getElementById("uploadSlipForm");
        if (x.style.display === "none") {
            x.style.display = "block";
        } else {
            x.style.display = "none";
        }
    }
</script>

app/views/bills/unconfirmed_index.html.erb
<div class="row justify-content-center">
  <div class="col-md-10 col-md-offset-1">
    <div class="card">
      <div class="card-header" style="text-align: center;">
        <h3 class="card-title">Unconfimed Bills for manual slip upload</h3>
      </div>

      <div class="card-body">
        <% if @bills.count > 0 %>
          <table class="table table-striped table-bordered table-list">
            <thead>
            <tr>
              <th class="hidden-xs">#</th>
              <th>Bill ID</th>
              <th>User ID</th>
              <th>Issued Date</th>
              <th>Deadline</th>
              <th>View Details</th>
            </tr>
            </thead>
            <tbody>
            <% i = 1 %>
            <% @bills.each do |b| %>
              <%= render 'bills/unconfirmed_row', bill: b, order: i %>
              <% i = i + 1 %>
            <% end %>
            </tbody>
          </table>

        <% else %>
          <p> All user Attachment are already confirmed</p>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/bills/unconfirmed_show.html.erb
<div class="row justify-content-center">
  <div class="col-lg-6 col-lg-offset-3">
    <div class="card">
      <div class="card-header" style="text-align: center;">
        <h3 class="card-title">Bill Details: Reference ID <%= @bill.id %></h3>
      </div>
      <div class="card-body" style="text-align: center;">
        <% if @bill.payment_evidence.exists? %>
          <%= image_tag @bill.payment_evidence.url, class: "card-img-top" %>
          <p>Uploaded at <%= @bill.payment_evidence_updated_at %> </p>
        <% end %>
        <table class="table">
          <tbody>
          <tr>
            <td>Total Amount:</td>
            <td><%= @bill.total_amount %></td>
          </tr>
          <tr>
            <td>Payment Deadline:</td>
            <td> <%= @bill.payment_deadline %> </td>
          </tr>
          <tr>
            <td>Current payment method:</td>
            <% if @bill.payment_method.nil? %>
              <td> Not Selected</td>
            <% else %>
              <td> <%= @bill.payment_method %> </td>
            <% end %>
          </tr>
          </tbody>
        </table>
      </div>
      <div class="card-footer text-center">
        <%= link_to unconfirmed_bill_update_path(@bill.id, is_confirmed: true), method: :post, class: "btn btn-success" do %>
          <em class="fa fa-check"></em> Accept Payment
        <% end %>
        <%= link_to unconfirmed_bill_path(@bill.id), method: :post, class: "btn btn-danger" do %>
          <em class="fa fa-times"></em> Reject Payment
        <% end %>
      </div>
    </div>
  </div>
</div>